spring:
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers:
          - 47.99.88.28:9092
      bindings:
        input:  #通道名称 @Input(Sink.INPUT)
          consumer:            max-attempts: 1  #通道发送消息失败时的重试次数
          binder: kafka
          destination: test1
          content-type:  application/json
          group: input-group-1
         

