server:
  port: 8081
spring:
  cloud:
    stream:
      default-binder: kafka #默认的绑定器，
      kafka: #如果用的是rabbitMQ这里填 rabbit
        binder:
          brokers: #Kafka的消息中间件服务器地址
          - 47.99.88.28:9092
      bindings:
        output: #通道名称 对应代码中的 @Output(Source.OUTPUT)
          binder: kafka
          destination: test1 #消息发往的目的地，对应topic
          group: output-group-1 #对应kafka的group,防止重复消费
          content-type: application/json #消息的格式
          
    