spring:
  application:
    name: eureka-server

server:
  port: 8761

management:
  context-path: /mysting
# post /shutdown
endpoints:
  shutdown:
    enabled: true
  info:
    path: /appInfo
  health:
    path: /healthCheck

eureka:
  instance:
    instanceId: ${spring.application.name}:${random.int}
    hostname: localhost
  statusPageUrlPath: ${management.context-path}/${endpoints.info.path}
  healthCheckUrlPath: ${management.context-path}/${endpoints.health.path}
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/